language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: Test
      script: mvn clean test
    - stage: Verify
      script: mvn clean verify
    - stage: Install
      script: mvn clean install

#notification:
#  email: st.a.tarasenko@gmail.com
