language: java
jdk:
  - openjdk8

script:
  - mvn clean
  - mvn test
  - mvn install

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "./target/recognizing_1-1.0-SNAPSHOT.jar"
  cleanup: true
  overwrite: true
  on:
    tags: true

notifications:
  email: st.a.tarasenko@gmail.com
